# Main menu navigation (导航栏设置)
# see https://butterfly.js.org/posts/4aa8abbe/#導航菜單
# --------------------------------------

menu:
  主页: / || fas fa-home
  归档: /archives/ || fas fa-archive
  标签: /tags/ || fas fa-tags
  分类: /categories/ || fas fa-folder-open
  # Content||fas fa-list:
  # List||fas fa-list:
  #   Music: /music/ || fas fa-music
  #   Movie: /movies/ || fas fa-video
  # Link: /link/ || fas fa-link
  # 关于: /about/ || fa-solid fa-user
  日志: /shuoshuo/ || fas fa-comment-dots
nav:
  logo: # image
  display_title: true
  fixed: false # fixed navigation bar

# --------------------------------------


# Code Blocks (代码块设置)
# --------------------------------------

highlight_theme: light #  darker / pale night / light / ocean / mac / mac light / false
highlight_copy: true # copy button
highlight_lang: true # show the code language
highlight_shrink: false # true: shrink the code blocks / false: expand the code blocks | none: expand code blocks and hide the button
highlight_height_limit: 230 # unit: px
code_word_wrap: false

# --------------------------------------


# social settings (社交图标设置)
# 书写格式 图标名：url || 描述性文字 || color
social:
  fab fa-github: https://github.com/zhuxz0299 || Github
  fas fa-envelope: mailto:zhuxz0299@gmail.com || Email
  fa-brands fa-bilibili: https://space.bilibili.com/1040684632 || Bilibili


# Image (图片设置)
# -----------------------------------------------

# Favicon（网站图标）
favicon: /img/zxz.ico

# Avatar (头像)
avatar:
  img: /img/raiden.jpg
  effect: false

# banner image (顶部图)
disable_top_img: false

# footer image (页脚背景图)
footer_img: false

# Background (网站背景)
background: /img/violet_light.jpg

# category_per_img:
#   - blog: https://source.fomal.cc/img/default_cover_152.webp

# -----------------------------------------------


# Cover (文章封面)
cover:
  # display the cover or not (是否显示封面)
  index_enable: true
  aside_enable: true
  archives_enable: true
  # the position of cover in home page (封面显示的位置)
  # left/right/both
  position: both
  # When cover is not set, the default cover is displayed (randomly chosen) (当文章未设置封面时，显示默认封面（随机选择）)
  default_cover:
    - https://source.fomal.cc/img/default_cover_1.webp
    - https://source.fomal.cc/img/default_cover_2.webp
    - https://source.fomal.cc/img/default_cover_3.webp
    - https://source.fomal.cc/img/default_cover_4.webp
    - https://source.fomal.cc/img/default_cover_5.webp
    # - https://i.loli.net/2020/05/01/gkihqEjXxJ5UZ1C.jpg

# Post meta settings (文章信息设置)
post_meta:
  page: # Home Page
    date_type: created # created or updated or both 主页文章是创建日或者更新日或者都显示
    date_format: date # date/relative 显示日期还是相对日期
    categories: true # true or false 主页是否显示分类
    tags: true # true or false 主页是否显示标签
    label: true # true or false 显示描述性文字
  post:
    date_type: both # created or updated or both 主页文章是创建日或者更新日或者都显示
    date_format: date # date/relative 显示日期还是相对日期
    categories: true # true or false 主页是否显示分类
    tags: true # true or false 文章页是否显示标签
    label: true # true or false 显示描述性文字


# 首页设置
# -----------------------------------------------

# 首页顶部图
index_site_info_top: # 主页标题距离顶部距离  例如 300px/300em/300rem/10%
index_top_img_height: #主页top_img高度 例如 300px/300em/300rem  不能使用百分比

# 网站副标题
subtitle:
  enable: false

# 首页卡片布局
index_layout: 3 # 从提供的几种布局中进行选择 1-7

# 主页文章节选（就是主页卡片上显示的文章摘要）
# method：显示文章内容的方式，有四种可供选择
# 1 - 只显示 description
# 2 - 优先选择 description，如果没有配置 description，则显示自动节选的内容
# 3 - 只显示自动节选
# 4 - 不显示文章内容
index_post_content:
  method: 2
  length: 100 # 文章节选的字数

# -----------------------------------------------


# 文章页设置
# -----------------------------------------------

# TOC 目录
toc:
  post: true
  page: false
  number: true
  expand: false
  style_simple: true # for post
  scroll_percent: false

# 版权信息
post_copyright:
  enable: true
  decode: true
  author_href:
  license: CC BY-NC-SA 4.0
  license_url: https://creativecommons.org/licenses/by-nc-sa/4.0/

# 相关文章 （相关文章推荐的原理是根据文章 tags 的比重来推荐）
related_post:
  enable: true
  limit: 6 # 显示推荐文章数目
  date_type: created # or created or updated 文章日期显示创建日或者更新日

# 文章分页按钮（上一篇/下一篇文章）
post_pagination: false

# 文章过期提醒
# Displays outdated notice for a post
noticeOutdate:
  enable: false
  style: flat # style: simple/flat
  limit_day: 500 # When will it be shown
  position: top # position: top/bottom
  message_prev: It has been
  message_next: days since the last update, the content of the article may be outdated.

# -----------------------------------------------


# 页脚设置
# -----------------------------------------------

# 博客年份
footer:
  owner:
    enable: true
    since: 2023
  custom_text:
  copyright: false # Copyright of theme and framework

# footer_beautify (页脚徽标美化)
# 需要额外安装插件：npm install hexo-butterfly-footer-beautify --save
# TODO 这个没有成功显示
# 页脚计时器：[Native JS Timer](https://akilar.top/posts/b941af/)
# 页脚徽标：[Add Github Badge](https://akilar.top/posts/e87ad7f8/)
footer_beautify:
  enable:
    timer: false # 计时器开关
    bdage: true # 徽标开关
  priority: 5 #过滤器优先权
  enable_page: all # 应用页面
  exclude: #屏蔽页面
    # - /posts/
    # - /about/
  layout: # 挂载容器类型
    type: id
    name: footer-wrap
    index: 0
  # 计时器部分配置项
  runtime_js: https://npm.elemecdn.com/hexo-butterfly-footer-beautify@1.0.0/lib/runtime.js
  runtime_css: https://npm.elemecdn.com/hexo-butterfly-footer-beautify@1.0.0/lib/runtime.css
  # 徽标部分配置项
  swiperpara: 0 #若非0，则开启轮播功能，每行徽标个数
  bdageitem:
    - link: https://hexo.io/ #徽标指向网站链接
      shields: https://img.shields.io/badge/Frame-Hexo-blue?style=flat&logo=hexo #徽标API
      message: 博客框架为Hexo_v7.3.0 #徽标提示语
    - link: https://butterfly.js.org/
      shields: https://img.shields.io/badge/Theme-Butterfly-6513df?style=flat&logo=bitdefender
      message: 主题版本Butterfly_v4.7.0
    - link: https://github.com/
      shields: https://img.shields.io/badge/Source-Github-d021d6?style=flat&logo=GitHub
      message: 本站项目由Github托管
    - link: http://creativecommons.org/licenses/by-nc-sa/4.0/
      shields: https://img.shields.io/badge/Copyright-BY--NC--SA%204.0-d42328?style=flat&logo=Claris
      message: 本站采用知识共享署名-非商业性使用-相同方式共享4.0国际许可协议进行许可
  swiper_css: https://npm.elemecdn.com/hexo-butterfly-swiper/lib/swiper.min.css
  swiper_js: https://npm.elemecdn.com/hexo-butterfly-swiper/lib/swiper.min.js
  swiperbdage_init_js: https://npm.elemecdn.com/hexo-butterfly-footer-beautify/lib/swiperbdage_init.min.js

# -----------------------------------------------


# Aside (侧边栏设置)
aside:
  enable: true
  hide: false
  button: true
  mobile: true # display on mobile
  position: right # left or right
  # font-size: 12px
  display:
    archive: true
    tag: true
    category: true
  card_author:
    enable: true
    description:
    button:
      enable: true
      icon: fab fa-github
      text: Follow Me
      link: https://github.com/zhuxz0299
  card_announcement:
    enable: false
    content: This is my Blog
  card_recent_post:
    enable: false
    limit: 5 # if set 0 will show all
    sort: date # date or updated
    sort_order: # Don't modify the setting unless you know how it works
  card_newest_comments:
    enable: true
    sort_order:
    limit: 6
    # Unit: mins, save data to localStorage
    storage: 10
    avatar: true
  card_categories:
    enable: true
    limit: 8 # if set 0 will show all
    expand: none # none/true/false
    sort_order: # Don't modify the setting unless you know how it works
  card_tags:
    enable: true
    limit: 40 # if set 0 will show all
    color: false
    orderby: random # Order of tags, random/name/length
    order: 1 # Sort of order. 1, asc for ascending; -1, desc for descending
    sort_order: # Don't modify the setting unless you know how it works
  card_archives:
    enable: true
    type: monthly # yearly or monthly
    format: MMMM YYYY # eg: YYYY年MM月
    order: -1 # Sort of order. 1, asc for ascending; -1, desc for descending
    limit: 8 # if set 0 will show all
    sort_order: # Don't modify the setting unless you know how it works
  card_post_series:
    enable: true
    # The title shows the series name
    series_title: false
    # Order by title or date
    orderBy: 'date'
    # Sort of order. 1, asc for ascending; -1, desc for descending
    order: -1
  card_webinfo:
    enable: true
    post_count: true
    last_push_date: true
    sort_order:
    # Time difference between publish date and now
    # Formal: Month/Day/Year Time or Year/Month/Day Time
    # Leave it empty if you don't enable this feature
    runtime_date:


# 右下角按钮
# -----------------------------------------------

# 阅读模式
readmode: false

# 夜间模式
darkmode:
  enable: true
  # Toggle Button to switch dark/light mode
  button: true
  # Switch dark/light mode automatically (自動切換 dark mode和 light mode)
  # autoChangeMode: 1  Following System Settings, if the system doesn't support dark mode, it will switch dark mode between 6 pm to 6 am
  # autoChangeMode: 2  Switch dark mode between 6 pm to 6 am
  # autoChangeMode: false
  autoChangeMode: false

# 滚动状态百分比
rightside_scroll_percent: true

# 右下角按钮排序（非必要不修改）
rightside_item_order:
  enable: false
  hide: # readmode,translate,darkmode,hideAside
  show: # toc,chat,comment

# -----------------------------------------------


# 全局配置
# -----------------------------------------------

# 页面锚点
anchor:
  button:
    enable: false
    always_show: false
    icon: # the unicode value of Font Awesome icon, such as '\3423'
  auto_update: false # when you scroll in post, the URL will update according to header id.

# 图片描述 （是否显示 Alt 文本作为图片描述）
photofigcaption: false

# 复制相关配置
# 可配置网站是否可以复制、复制的内容是否添加版权信息
copy:
  enable: true
  copyright:
    enable: false
    limit_count: 50

# 字数统计
# 插件： npm install hexo-wordcount --save
wordcount:
  enable: true
  post_wordcount: true
  min2read: true
  total_wordcount: true

# 访问人数统计 (busuanzi)
busuanzi:
  site_uv: false
  site_pv: false
  page_pv: false


# Math (数学公式渲染)
# -----------------------------------------------
math:
  # Choose: mathjax, katex
  # Leave it empty if you don't need math
  use: katex
  per_page: false
  hide_scrollbar: true

# 使用 katex 需要调整插件
# npm un hexo-renderer-marked --save # 如果有安装这个的话，卸载
# npm un hexo-renderer-kramed --save # 如果有安装这个的话，卸载

# npm i hexo-renderer-markdown-it --save # 需要安装这个渲染插件
# npm install katex @renbaoshuo/markdown-it-katex #需要安装这个katex插件

katex:
  # Enable the copy KaTeX formula
  copy_tex: false

# -----------------------------------------------


# 搜索设置
# -----------------------------------------------
search:
  # Choose: algolia_search / local_search / docsearch
  # leave it empty if you don't need search
  use: local_search
  placeholder:
  # https://github.com/wzpan/hexo-generator-search 中要求的配置
  path: search.xml
  field: post
  content: true

# Local Search
# 需要安装 hexo-generator-searchdb 或者 hexo-generator-search，根据它的文档去做相应配置
local_search:
  # Preload the search data when the page loads.
  preload: true
  # Show top n results per article, show all results by setting to -1
  top_n_per_article: 1
  # Unescape html strings to the readable one.
  unescape: false
  CDN:

# -----------------------------------------------


# 分享设置
# -----------------------------------------------

share:
  # Choose: sharejs / addtoany
  # Leave it empty if you don't need share
  use: sharejs

# Share.js
# https://github.com/overtrue/share.js
sharejs:
  sites: facebook,twitter,wechat,weibo,qq

# -----------------------------------------------


# 评论-在线聊天-分析统计-广告-网站验证跳过


# Comments (评论系统设置)
# -----------------------------------------------
comments:
  # Up to two comments system, the first will be shown as default
  # Choose: Disqus/Disqusjs/Livere/Gitalk/Valine/Waline/Utterances/Facebook Comments/Twikoo/Giscus/Remark42/Artalk
  use: Twikoo
  text: true # Display the comment name next to the button
  # lazyload: The comment system will be load when comment element enters the browser's viewport.
  # If you set it to true, the comment count will be invalid
  lazyload: true
  count: true # Display comment count in post's top_img
  card_post_count: false # Display comment count in Home Page

# Twikoo
# https://github.com/imaegoo/twikoo
twikoo:
  envId: https://twikoo-api-mu-three.vercel.app/
  region:
  visitor: false
  option:

# -----------------------------------------------


# 美化/特效
# -----------------------------------------------

# Preloader (页面加载动画)
preloader:
  enable: false
  # source
  # 1. fullpage-loading
  # 2. pace (progress bar)
  source: 1
  # pace theme (see https://codebyzach.github.io/pace/)
  pace_css_url:

# Default display mode (网站默认的显示模式)
# light (default) / dark
display_mode: dark

# Beautify (美化頁面顯示)
beautify:
  enable: false
  field: post # site/post
  title-prefix-icon: # '\f0c1'
  title-prefix-icon-color: # '#F47466'

# Global font settings
# Don't modify the following settings unless you know how they work (非必要不要修改)
font:
  global-font-size: 16px
  code-font-size: 15px
  font-family:
  code-font-family:

# Font settings for the site title and site subtitle
# 左上角网站名字 主页居中网站名字
blog_title_font:
  font_link:
  font-family:

# The setting of divider icon (水平分隔线图标设置)
hr_icon:
  enable: true
  icon: # the unicode value of Font Awesome icon, such as '\3423'
  icon-top:

# -----------------------------------------------



# 图片大图查看模式
# Choose: fancybox / medium_zoom
# https://github.com/francoischalifour/medium-zoom
# https://fancyapps.com/fancybox/
# Leave it empty if you don't need lightbox
lightbox: fancybox


# 标签外挂
# Note (Bootstrap Callout)
note:
  # Note tag style values:
  #  - simple    bs-callout old alert style. Default.
  #  - modern    bs-callout new (v2-v3) alert style.
  #  - flat      flat callout style with background, like on Mozilla or StackOverflow.
  #  - disabled  disable all CSS styles import of note tag.
  style: flat
  icons: true
  border_radius: 3
  # Offset lighter of background in % for modern and flat styles (modern: -12 | 12; flat: -18 | 6).
  # Offset also applied to label tag variables. This option can work with disabled note tag.
  light_bg_offset: 0

# Mermaid
# https://github.com/mermaid-js/mermaid
mermaid:
  enable: true
  # Write Mermaid diagrams using code blocks
  code_write: true
  # built-in themes: default / forest / dark / neutral
  theme:
    light: default
    dark: dark


# Open graph meta tags
# 用于社交媒体分享时显示丰富的链接预览
# https://hexo.io/docs/helpers#open-graph
Open_Graph_meta:
  enable: true
  option:


# 开启 css_prefix 后，会自动为一些 CSS 增加前缀。
# Add the vendor prefixes to ensure compatibility
css_prefix: true


# CDN Settings (内容分发网络设置)
# Don't modify the following settings unless you know how they work
CDN:
  # The CDN provider for internal and third-party scripts
  # Options for both: local/jsdelivr/unpkg/cdnjs/custom
  # Note: Dev version can only use 'local' for internal scripts
  # Note: When setting third-party scripts to 'local', you need to install hexo-butterfly-extjs
  internal_provider: local
  third_party_provider: jsdelivr

  # Add version number to url, true or false
  version: false


# Inject (自定义CSS/JS代码)
# Insert the code to head (before '</head>' tag) and the bottom (before '</body>' tag)
# 插入代码到头部 </head> 之前 和 底部 </body> 之前
inject:
  head:
  # 自定义css
    - <link rel="stylesheet" href="/css/only_bg_img.css" media="defer" onload="this.media='all'">
    - <link rel="stylesheet" href="/css/cursor.css" media="defer" onload="this.media='all'">
    - <link rel="stylesheet" href="/css/nav_bar.css" media="defer" onload="this.media='all'">
    - <link rel="stylesheet" href="/css/page_border.css" media="defer" onload="this.media='all'">
    - <link rel="stylesheet" href="/css/font.css" media="defer" onload="this.media='all'">
    - <link rel="stylesheet" href="/css/scroll_bar.css" media="defer" onload="this.media='all'">
    # - <link rel="stylesheet" href="/css/category.css">
  bottom:
    - <script defer src="/js/cursor.js"></script>
    # - <script defer src="/js/category.js"></script>



# Other settings (其他设置，配置文件里面有但是没有详细说明的设置项)
# -----------------------------------------------
# Replace Broken Images (无法显示图片时的替代图片)
error_img:
  flink: /img/friend_404.gif
  post_page: /img/404.jpg

# A simple 404 page (not found) (简单的404页面（未找到）)
error_404:
  enable: false
  subtitle: 'Page Not Found'
  background: https://i.loli.net/2020/05/19/aKOcLiyPl2JQdFD.png

# Lazyload (图片懒加载)
# https://github.com/verlok/vanilla-lazyload
lazyload:
  enable: true
  field: site # site/post
  placeholder:
  blur: false

# 文章卡片出场动画
wowjs:
  enable: false #控制动画开关。true是打开，false是关闭
  priority: 10 #过滤器优先级
  mobile: false #移动端是否启用，默认移动端禁用
  animateitem:
    - class: recent-post-item #必填项，需要添加动画的元素的class
      style: animate__zoomIn #必填项，需要添加的动画
      duration: 1s #选填项，动画持续时间，单位可以是ms也可以是s。例如3s，700ms。
      delay: 500ms #选填项，动画开始的延迟时间，单位可以是ms也可以是s。例如3s，700ms。
      offset: 100 #选填项，开始动画的距离（相对浏览器底部）
      iteration: 1 #选填项，动画重复的次数
    - class: card-widget
      style: animate__zoomIn
  animate_css: https://npm.elemecdn.com/hexo-butterfly-wowjs/lib/animate.min.css
  wow_js: https://npm.elemecdn.com/hexo-butterfly-wowjs/lib/wow.min.js
  wow_init_js: https://npm.elemecdn.com/hexo-butterfly-wowjs/lib/wow_init.js


# Sitemap (网站地图设置, 供搜索引擎使用)
# TODO后续似乎还有需要配置的？
sitemap:
  path: 
  template:
  template_txt:
  rel: false
  tags: true
  categories: true


# Archive Generator (归档页面设置)
archive_generator:
  enabled: true
  per_page: 15